spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-order-service
    username: root
    password: utzpassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8000